/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IaRouteImport } from './routes/ia'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VendasPdvRouteImport } from './routes/vendas/pdv'
import { Route as VendasOperacaoRouteImport } from './routes/vendas/operacao'
import { Route as VendasAssinantesRouteImport } from './routes/vendas/assinantes'
import { Route as FinanceiroVisaoGeralRouteImport } from './routes/financeiro/visao-geral'
import { Route as FinanceiroDreRouteImport } from './routes/financeiro/dre'
import { Route as CadastrosUsuariosRouteImport } from './routes/cadastros/usuarios'
import { Route as CadastrosServicosRouteImport } from './routes/cadastros/servicos'
import { Route as CadastrosProdutosRouteImport } from './routes/cadastros/produtos'
import { Route as CadastrosPlanosRouteImport } from './routes/cadastros/planos'
import { Route as CadastrosFranquiasRouteImport } from './routes/cadastros/franquias'
import { Route as CadastrosFornecedoresRouteImport } from './routes/cadastros/fornecedores'
import { Route as CadastrosCuponsRouteImport } from './routes/cadastros/cupons'
import { Route as CadastrosClientesRouteImport } from './routes/cadastros/clientes'
import { Route as CadastrosCentrosDeCustoRouteImport } from './routes/cadastros/centros-de-custo'

const IaRoute = IaRouteImport.update({
  id: '/ia',
  path: '/ia',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendasPdvRoute = VendasPdvRouteImport.update({
  id: '/vendas/pdv',
  path: '/vendas/pdv',
  getParentRoute: () => rootRouteImport,
} as any)
const VendasOperacaoRoute = VendasOperacaoRouteImport.update({
  id: '/vendas/operacao',
  path: '/vendas/operacao',
  getParentRoute: () => rootRouteImport,
} as any)
const VendasAssinantesRoute = VendasAssinantesRouteImport.update({
  id: '/vendas/assinantes',
  path: '/vendas/assinantes',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroVisaoGeralRoute = FinanceiroVisaoGeralRouteImport.update({
  id: '/financeiro/visao-geral',
  path: '/financeiro/visao-geral',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroDreRoute = FinanceiroDreRouteImport.update({
  id: '/financeiro/dre',
  path: '/financeiro/dre',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastrosUsuariosRoute = CadastrosUsuariosRouteImport.update({
  id: '/cadastros/usuarios',
  path: '/cadastros/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastrosServicosRoute = CadastrosServicosRouteImport.update({
  id: '/cadastros/servicos',
  path: '/cadastros/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastrosProdutosRoute = CadastrosProdutosRouteImport.update({
  id: '/cadastros/produtos',
  path: '/cadastros/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastrosPlanosRoute = CadastrosPlanosRouteImport.update({
  id: '/cadastros/planos',
  path: '/cadastros/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastrosFranquiasRoute = CadastrosFranquiasRouteImport.update({
  id: '/cadastros/franquias',
  path: '/cadastros/franquias',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastrosFornecedoresRoute = CadastrosFornecedoresRouteImport.update({
  id: '/cadastros/fornecedores',
  path: '/cadastros/fornecedores',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastrosCuponsRoute = CadastrosCuponsRouteImport.update({
  id: '/cadastros/cupons',
  path: '/cadastros/cupons',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastrosClientesRoute = CadastrosClientesRouteImport.update({
  id: '/cadastros/clientes',
  path: '/cadastros/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastrosCentrosDeCustoRoute = CadastrosCentrosDeCustoRouteImport.update({
  id: '/cadastros/centros-de-custo',
  path: '/cadastros/centros-de-custo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ia': typeof IaRoute
  '/cadastros/centros-de-custo': typeof CadastrosCentrosDeCustoRoute
  '/cadastros/clientes': typeof CadastrosClientesRoute
  '/cadastros/cupons': typeof CadastrosCuponsRoute
  '/cadastros/fornecedores': typeof CadastrosFornecedoresRoute
  '/cadastros/franquias': typeof CadastrosFranquiasRoute
  '/cadastros/planos': typeof CadastrosPlanosRoute
  '/cadastros/produtos': typeof CadastrosProdutosRoute
  '/cadastros/servicos': typeof CadastrosServicosRoute
  '/cadastros/usuarios': typeof CadastrosUsuariosRoute
  '/financeiro/dre': typeof FinanceiroDreRoute
  '/financeiro/visao-geral': typeof FinanceiroVisaoGeralRoute
  '/vendas/assinantes': typeof VendasAssinantesRoute
  '/vendas/operacao': typeof VendasOperacaoRoute
  '/vendas/pdv': typeof VendasPdvRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ia': typeof IaRoute
  '/cadastros/centros-de-custo': typeof CadastrosCentrosDeCustoRoute
  '/cadastros/clientes': typeof CadastrosClientesRoute
  '/cadastros/cupons': typeof CadastrosCuponsRoute
  '/cadastros/fornecedores': typeof CadastrosFornecedoresRoute
  '/cadastros/franquias': typeof CadastrosFranquiasRoute
  '/cadastros/planos': typeof CadastrosPlanosRoute
  '/cadastros/produtos': typeof CadastrosProdutosRoute
  '/cadastros/servicos': typeof CadastrosServicosRoute
  '/cadastros/usuarios': typeof CadastrosUsuariosRoute
  '/financeiro/dre': typeof FinanceiroDreRoute
  '/financeiro/visao-geral': typeof FinanceiroVisaoGeralRoute
  '/vendas/assinantes': typeof VendasAssinantesRoute
  '/vendas/operacao': typeof VendasOperacaoRoute
  '/vendas/pdv': typeof VendasPdvRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ia': typeof IaRoute
  '/cadastros/centros-de-custo': typeof CadastrosCentrosDeCustoRoute
  '/cadastros/clientes': typeof CadastrosClientesRoute
  '/cadastros/cupons': typeof CadastrosCuponsRoute
  '/cadastros/fornecedores': typeof CadastrosFornecedoresRoute
  '/cadastros/franquias': typeof CadastrosFranquiasRoute
  '/cadastros/planos': typeof CadastrosPlanosRoute
  '/cadastros/produtos': typeof CadastrosProdutosRoute
  '/cadastros/servicos': typeof CadastrosServicosRoute
  '/cadastros/usuarios': typeof CadastrosUsuariosRoute
  '/financeiro/dre': typeof FinanceiroDreRoute
  '/financeiro/visao-geral': typeof FinanceiroVisaoGeralRoute
  '/vendas/assinantes': typeof VendasAssinantesRoute
  '/vendas/operacao': typeof VendasOperacaoRoute
  '/vendas/pdv': typeof VendasPdvRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ia'
    | '/cadastros/centros-de-custo'
    | '/cadastros/clientes'
    | '/cadastros/cupons'
    | '/cadastros/fornecedores'
    | '/cadastros/franquias'
    | '/cadastros/planos'
    | '/cadastros/produtos'
    | '/cadastros/servicos'
    | '/cadastros/usuarios'
    | '/financeiro/dre'
    | '/financeiro/visao-geral'
    | '/vendas/assinantes'
    | '/vendas/operacao'
    | '/vendas/pdv'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ia'
    | '/cadastros/centros-de-custo'
    | '/cadastros/clientes'
    | '/cadastros/cupons'
    | '/cadastros/fornecedores'
    | '/cadastros/franquias'
    | '/cadastros/planos'
    | '/cadastros/produtos'
    | '/cadastros/servicos'
    | '/cadastros/usuarios'
    | '/financeiro/dre'
    | '/financeiro/visao-geral'
    | '/vendas/assinantes'
    | '/vendas/operacao'
    | '/vendas/pdv'
  id:
    | '__root__'
    | '/'
    | '/ia'
    | '/cadastros/centros-de-custo'
    | '/cadastros/clientes'
    | '/cadastros/cupons'
    | '/cadastros/fornecedores'
    | '/cadastros/franquias'
    | '/cadastros/planos'
    | '/cadastros/produtos'
    | '/cadastros/servicos'
    | '/cadastros/usuarios'
    | '/financeiro/dre'
    | '/financeiro/visao-geral'
    | '/vendas/assinantes'
    | '/vendas/operacao'
    | '/vendas/pdv'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IaRoute: typeof IaRoute
  CadastrosCentrosDeCustoRoute: typeof CadastrosCentrosDeCustoRoute
  CadastrosClientesRoute: typeof CadastrosClientesRoute
  CadastrosCuponsRoute: typeof CadastrosCuponsRoute
  CadastrosFornecedoresRoute: typeof CadastrosFornecedoresRoute
  CadastrosFranquiasRoute: typeof CadastrosFranquiasRoute
  CadastrosPlanosRoute: typeof CadastrosPlanosRoute
  CadastrosProdutosRoute: typeof CadastrosProdutosRoute
  CadastrosServicosRoute: typeof CadastrosServicosRoute
  CadastrosUsuariosRoute: typeof CadastrosUsuariosRoute
  FinanceiroDreRoute: typeof FinanceiroDreRoute
  FinanceiroVisaoGeralRoute: typeof FinanceiroVisaoGeralRoute
  VendasAssinantesRoute: typeof VendasAssinantesRoute
  VendasOperacaoRoute: typeof VendasOperacaoRoute
  VendasPdvRoute: typeof VendasPdvRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ia': {
      id: '/ia'
      path: '/ia'
      fullPath: '/ia'
      preLoaderRoute: typeof IaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendas/pdv': {
      id: '/vendas/pdv'
      path: '/vendas/pdv'
      fullPath: '/vendas/pdv'
      preLoaderRoute: typeof VendasPdvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendas/operacao': {
      id: '/vendas/operacao'
      path: '/vendas/operacao'
      fullPath: '/vendas/operacao'
      preLoaderRoute: typeof VendasOperacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendas/assinantes': {
      id: '/vendas/assinantes'
      path: '/vendas/assinantes'
      fullPath: '/vendas/assinantes'
      preLoaderRoute: typeof VendasAssinantesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro/visao-geral': {
      id: '/financeiro/visao-geral'
      path: '/financeiro/visao-geral'
      fullPath: '/financeiro/visao-geral'
      preLoaderRoute: typeof FinanceiroVisaoGeralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro/dre': {
      id: '/financeiro/dre'
      path: '/financeiro/dre'
      fullPath: '/financeiro/dre'
      preLoaderRoute: typeof FinanceiroDreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastros/usuarios': {
      id: '/cadastros/usuarios'
      path: '/cadastros/usuarios'
      fullPath: '/cadastros/usuarios'
      preLoaderRoute: typeof CadastrosUsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastros/servicos': {
      id: '/cadastros/servicos'
      path: '/cadastros/servicos'
      fullPath: '/cadastros/servicos'
      preLoaderRoute: typeof CadastrosServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastros/produtos': {
      id: '/cadastros/produtos'
      path: '/cadastros/produtos'
      fullPath: '/cadastros/produtos'
      preLoaderRoute: typeof CadastrosProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastros/planos': {
      id: '/cadastros/planos'
      path: '/cadastros/planos'
      fullPath: '/cadastros/planos'
      preLoaderRoute: typeof CadastrosPlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastros/franquias': {
      id: '/cadastros/franquias'
      path: '/cadastros/franquias'
      fullPath: '/cadastros/franquias'
      preLoaderRoute: typeof CadastrosFranquiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastros/fornecedores': {
      id: '/cadastros/fornecedores'
      path: '/cadastros/fornecedores'
      fullPath: '/cadastros/fornecedores'
      preLoaderRoute: typeof CadastrosFornecedoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastros/cupons': {
      id: '/cadastros/cupons'
      path: '/cadastros/cupons'
      fullPath: '/cadastros/cupons'
      preLoaderRoute: typeof CadastrosCuponsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastros/clientes': {
      id: '/cadastros/clientes'
      path: '/cadastros/clientes'
      fullPath: '/cadastros/clientes'
      preLoaderRoute: typeof CadastrosClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastros/centros-de-custo': {
      id: '/cadastros/centros-de-custo'
      path: '/cadastros/centros-de-custo'
      fullPath: '/cadastros/centros-de-custo'
      preLoaderRoute: typeof CadastrosCentrosDeCustoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IaRoute: IaRoute,
  CadastrosCentrosDeCustoRoute: CadastrosCentrosDeCustoRoute,
  CadastrosClientesRoute: CadastrosClientesRoute,
  CadastrosCuponsRoute: CadastrosCuponsRoute,
  CadastrosFornecedoresRoute: CadastrosFornecedoresRoute,
  CadastrosFranquiasRoute: CadastrosFranquiasRoute,
  CadastrosPlanosRoute: CadastrosPlanosRoute,
  CadastrosProdutosRoute: CadastrosProdutosRoute,
  CadastrosServicosRoute: CadastrosServicosRoute,
  CadastrosUsuariosRoute: CadastrosUsuariosRoute,
  FinanceiroDreRoute: FinanceiroDreRoute,
  FinanceiroVisaoGeralRoute: FinanceiroVisaoGeralRoute,
  VendasAssinantesRoute: VendasAssinantesRoute,
  VendasOperacaoRoute: VendasOperacaoRoute,
  VendasPdvRoute: VendasPdvRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
